// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotePrice.Infrastructure.Database;

#nullable disable

namespace QuotePrice.Sqlite.Migrations
{
    [DbContext(typeof(QuoteDbContext))]
    [Migration("20230219221715_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("QuotePrice.Infrastructure.Database.Entities.DbQuote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Ask")
                        .HasColumnType("REAL");

                    b.Property<double?>("Bid")
                        .HasColumnType("REAL");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Timestamp")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("quotes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
