version: '3.8'

services:
  postgres:
    container_name: postgres_database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5444:5432"


volumes:
  postgres-db:
    driver: local